itzsaga/slack-list

.travis.yml

This is needed for the Greenkeeper Bot to work.

Add TravisCI.

---

src/about.html
src/index.html
webpack.config.js

A few things going on here:
- I'm playing around with the [Hero Banner](http://bulma.io/documentation/layout/hero/) that Bulma has. Would like thoughts about it.
- Need to make an overall decision in what the top of the site should look like.
- Thinking we can use the `.hero-foot` class and create in-page navigation via anchor tags on pages that would warrant it.
- The first pass at some copy for that page which could probably be written better. I'd like to present a "story" that can continue to be added to as time passes. Edits greatly appreciated.
- I added a footer element with some stuff. Would like input on what the footer should contain. Put some stuff but by no means does it need to stay how it is.
_Note:_ This should probably not be one PR. Too many things going on. My bad.

Add About page

---

src/list.html

added Knoxdev

---

package.json

chore(package): update cypress to version 2.0.1

---

src/list.html

Added new listing for Louisville

Issue #26 - added listing for Louisville.IO including Kentucky category

---

src/list.html

Closes Issue #20 
This native Oregonian added both PDX and Oregon to the list. Wooo!

added PDX to the list

---

src/list.html

Issue #33 
Added Midwest Dev Chat to list, added Midwest regional heading

added midwest dev chat -jw

---

src/list.html

added New York network

---

src/list.html

Added Software Craftmaship to list.html

---

src/list.html

added Open Austin

---

src/list.html

Added Colorado New Tech slack channel

---

src/list.html

Added DFWStartupCommunity to list

---

package.json

fix(package): update sass-loader to version 7.0.1

---

src/list.html

adding philadelphia to the list

---

package.json
yarn.lock

Greenkeeper/cypress 3.8.0

---

cypress/integration/index_spec.js
src/data/list.js

Added the Rands Leadership Slack to the list under IT.

add the rands leadership slack'

---

.github/workflows/test.yml
README.md

Remove the three actions in favor of a single action using the version of Node defined in the `.nvmrc` file.

Slim down actions

---

cypress/integration/index_spec.js
src/data/list.js

feat: add boro.dev

---

cypress/integration/index_spec.js
src/data/list.js

feat: add bluegrass developers guild

---

cypress/integration/index_spec.js
src/components/hero.js
src/data/list.js
src/pages/index.js

Adds Penny University, a peer to peer learning community, to the list under miscellaneous. The section for miscellaneous did not exist yet, so I added that as well.

feat: add penny university

---

cypress/integration/index_spec.js
src/data/list.js

Add AfriSplash Remotely to list
